development:
  adapter: postgresql
  encoding: unicode
  database: yolk_development
  pool: 5
  username: yolk
  password: yolk

test:
  adapter: postgresql
  encoding: unicode
  database: yolk_test
  pool: 5
  username: yolk
  password: yolk

